# Generated by Django 4.1.7 on 2023-02-22 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
