# Generated by Django 4.1.7 on 2023-03-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_rename_data_created_card_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('comments', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='answer',
        ),
    ]
