# Generated by Django 4.1.7 on 2023-03-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_flashcard_remove_card_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='answer',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
