# Generated by Django 4.1.7 on 2023-03-12 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_card_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='comments',
        ),
        migrations.CreateModel(
            name='FlashcardAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(auto_created=1)),
                ('choice_text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcard.flashcard')),
            ],
        ),
    ]
