# Generated by Django 4.1.7 on 2023-03-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0006_remove_flashcard_comments_flashcardanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcardanswer',
            old_name='choice_text',
            new_name='answer',
        ),
    ]
