# Generated by Django 4.1.7 on 2023-03-12 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0007_rename_choice_text_flashcardanswer_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(auto_created=1)),
                ('answer', models.CharField(max_length=200)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcard.flashcard')),
            ],
        ),
        migrations.DeleteModel(
            name='FlashcardAnswer',
        ),
    ]
